FROM mcr.microsoft.com/devcontainers/python:0-3.11

RUN pip install --upgrade pip
RUN pip install python-dotenv
RUN pip install streamlit
RUN pip install openai
RUN pip install langchain

RUN apt-get install -y git
