FROM mcr.microsoft.com/devcontainers/python:0-3.11

RUN pip3 install --upgrade pip
RUN pip3 install python-dotenv
RUN pip3 install streamlit
RUN pip3 install openai
RUN pip3 install langchain

RUN apt-get install -y git
